name: ci

concurrency:
  group: ci

on:
  push:
    # branches:
    #   - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    permissions:
      packages: write
    steps:
      - name: Install debian dependencies
        run: |
          apt-get -yqq update
          apt-get -yqq upgrade
          apt-get -yqq install --no-install-recommends \
            build-essential \
            ca-certificates \
            curl \
            file \
            g++ \
            gcc \
            gfortran \
            git \
            gnupg2 \
            iproute2 \
            locales \
            make \
            mercurial \
            subversion \
            python3 \
            python3-boto3 \
            unzip \
            zstd
          locale-gen en_US.UTF-8


      - uses: actions/checkout@v4

      - uses: viperML/spack-buildcache-action@main
        with:
          environment: .

      - run: which -a cmake
