name: ci

concurrency:
  group: ci

on:
  push:
    # branches:
    #   - master
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: viperML/spack-buildcache-action@main
        with:
          environment: .

      - run: which -a cmake
